### ISSUE TITLE
Discuss possibility to use repo-specific server urls

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [sociomantic-tsunami/kelpie#1]
I found a way to specify per-project  sha-base-urls (the url where we fetch the pushed shas from:

```
URLSHA=$(echo "https://ci.sociomantic.com/hook-data/incremental-diff/hashes/" | git hash-object --stdin -w)
git update-ref refs/meta/incremental-diff-url $URLSHA
git push origin refs/meta/incremental-diff-url
```

With the github api I can then simply fetch the reference `refs/meta/incremental-diff-url` and from that the blob object containing the URL.

This functionality is already implemented, however, there are certain voices ( @leandro-lucarella-sociomantic  ) who are sceptical of this approach

**Comment by leandro-lucarella-sociomantic** [comment]
I am less sceptical now that I understood that you are actually using the Git object database as a general database to store this info. I think is hackish, but reasonable and if we add to it the possibility to to also store the hash history too, it removes a very annoying problem of hosting these history and it might be more justified.

**Comment by leandro-lucarella-sociomantic** [comment]
Archiving as this repo was never really actively developed.
