### ISSUE TITLE
Make URL rule more specific

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/kelpie#4]
Right now the rule applies to `*://github.com/*`, which is maybe too generic, probably using `https://github.com/*/*/pull/*` (if this works as I imagine it would) will be better.

**Comment by mathias-baumann-sociomantic** [comment]
No, it wouldn't. Github doesn't actually reload the page when you follow links but does for a large part just AJAX requests and in-page refreshing. If we load the script only on `pull` match URLs it will often not be loaded when users navigated from the Pull-Request overview page to the Pull-Request page
