### ISSUE TITLE
Consider storing the PR hashes inside the repo 

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [sociomantic-tsunami/kelpie#5]
Using git objects and references we can use the repo as a kind of data base. We could (ab)use this to store the hashes directly in the repo instead of on an external server.

Pro:
- No extra storage place

Neg:
- needs push permission to the repo
- no clue of how long those objects will exist. probalby forever when git-references to them exist, but still
- would the repo be spammed with lots of references?

**Comment by leandro-lucarella-sociomantic** [comment]
> needs push permission to the repo

This one is a bit annoying but given that the hooks will have to be set by an admin it shouldn't be a huge deal to ask for a token with push permissions, I guess.

> no clue of how long those objects will exist. probalby forever when git-references to them exist, but still

Yeah, I think as long as there is a reference to them, they should survive

> would the repo be spammed with lots of references?

One ref/file per PR doesn't seem to be that bad, I guess...

**Comment by leandro-lucarella-sociomantic** [comment]
Archiving as this repo was never really actively developed.
