### ISSUE TITLE
Deleting doesn't show on diff

### ISSUE THREAD

**Issue by alaksiej-stankievicx-dunnhumby** [sociomantic-tsunami/kelpie#8]
I use this with greasemonkey. And I see only additions, changes, but not deletions (when I totally delete some piece of code, not modify).

**Comment by leandro-lucarella-sociomantic** [comment]
sociomantic-tsunami/kelp

**Comment by leandro-lucarella-sociomantic** [comment]
Archiving as this repo was never really actively developed.
