### ISSUE TITLE
Better handling of pushes without code changes

### ISSUE THREAD

**Issue by gkotian** [sociomantic-tsunami/kelpie#9]
Sometimes an author may push to a PR but without any actual code changes. For instance if a reviewer requested changes only to a commit message, or if the author wants to manually trigger a CI build.

When this happens, currently the `View changes` button is displayed, and on clicking it, just the `Close` link appears. This is not terribly bad, but I think the user experience can be improved.

One way would be to change the `Author pushed code changes at XXX` message to `Author pushed updated commit(s) without code changes at XXX` and not show the `View changes` button at all. Would this be feasible to implement?

**Comment by mathias-baumann-sociomantic** [comment]
probably.

**Comment by leandro-lucarella-sociomantic** [comment]
Archiving as this repo was never really actively developed.
